---
- name: roles/service/handlers/main.yml
  assert: { that: true, quiet: true }

- name: enable firewalld
  systemd:
    name: firewalld
    state: restarted
    enabled: yes
  become: yes

- name: restart httpd
  systemd:
    name: httpd
    state: restarted
    enabled: yes
  become: yes

- name: reload httpd
  systemd:
    name: httpd
    state: reloaded
    enabled: yes
  become: yes

- name: restart pm2
  systemd:
    name: pm2
    enabled: yes
    state: restarted
    daemon_reload: yes
  become: yes

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes
  become: yes

- name: restart grafana-server
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
  become: yes

- name: reload grafana-server
  systemd:
    name: grafana-server
    state: reloaded
    enabled: yes
  become: yes
