---
- name: roles/postgresql/tasks/postgresql.yml
  assert: { that: true, quiet: true }

- name: Enable PostgreSQL dnf module 
  command: dnf module -y enable postgresql
  become: true

- name: Install PostgreSQL
  dnf:
    name: 
      - postgresql-server
      - postgresql-devel
      - python3-psycopg2
  become: true

- name: Check if initdb has already done.
  stat:
    path: "/var/lib/pgsql/data/PG_VERSION"
  become: true
  register: pg_version

# - debug: var=pg_version

- name: Create a new PostgreSQL database cluster.
  command: postgresql-setup initdb
  when: not pg_version.stat.exists
  become: true

- name: Grant access from localhost
  template:
    src: pg_hba.conf
    dest: /var/lib/pgsql/data/
    mode: 0700
    owner: postgres
    group: postgres
  become: true

- name: Start and enable postgresql by default
  systemd:
    name: postgresql
    state: started
    enabled: true
  become: true

- name: Create symlink to log
  file:
    path: /var/log/pgsql
    src: /var/lib/pgsql/data/log
    state: link
  become: true
