---
- name: roles/389ds/tasks/main.yml
  meta: noop

- name: Install 389ds
  dnf:
    name: 389-ds-base
    state: present
  become: yes

- name: Deploy ds-template to /tmp
  template:
    src: ds-template.txt
    dest: /tmp
