---
- name: roles/gitlab/tasks/gitlab.yml
  assert: { that: true, quiet: true }

# See. https://about.gitlab.com/install/#almalinux

- name: Deploy repository file
  copy:
    src: gitlab-ee.repo
    dest: /etc/yum.repos.d/
  become: yes
# Preset gpgcheck=0 in repo file

- name: Create yum cache for binary
  dnf:
    update_cache: true
    disablerepo: '*'
    enablerepo: gitlab_gitlab-ee
  become: yes

- name: Create yum cache for source
  dnf:
    update_cache: true
    disablerepo: '*'
    enablerepo: gitlab_gitlab-ee-source
  become: yes

- name: Install gitlab
  dnf:
    name: "{{ GITLAB_PACKAGE_VER }}"
  environment:
    EXTERNAL_URL: https://{{ GITLAB_FQDN }}
  become: true
  when: not gitlab.stat.exists

- name: Download glab (Gitlab cli)
  get_url:
    url: "{{ GITLAB_GLAB_URL }}"
    dest: /tmp/

- name: Install glab
  dnf:
    name: "/tmp/{{ GITLAB_GLAB_RPM }}"
    disable_gpg_check: true
  become: true

- name: Add entry to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: ^127.0.0.1  {{ GITLAB_FQDN }}
    line: 127.0.0.1  {{ GITLAB_FQDN }}
  become: true

- name: Open firewall
  ansible.posix.firewalld:
    service: "{{ item }}"
    offline: false
    permanent: true
    state: enabled
  become: yes
  loop:
    - http
    - https
  tags: firewall

- name: Fix gitlab version
  lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: excludepkgs=gitlab-ee
    line: excludepkgs=gitlab-ee
  become: true

- name: Gitlab was successfully installed.
  assert: { that: true, quiet: true }

