---
- name: roles/gitlab/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Check if gitlab has already installed.
  stat:
    path: /etc/gitlab/
  register: gitlab

- debug: var=gitlab

- import_tasks: gitlab.yml
# when: not gitlab.stat.exists
