---
- name: roles/gitlab/tasks/main.yml
  assert: { that: true, quiet: true }

# See. https://about.gitlab.com/install/#almalinux

- name: Deploy repository file
  copy:
    src: gitlab-ee.repo
    dest: /etc/yum.repos.d/
  become: yes
# Preset gpgcheck=0 in repo file

- name: Create yum cache for binary
  dnf:
    update_cache: true
    disablerepo: '*'
    enablerepo: gitlab_gitlab-ee
  become: yes

- name: Create yum cache for source
  dnf:
    update_cache: true
    disablerepo: '*'
    enablerepo: gitlab_gitlab-ee-source
  become: yes

- name: Install gitlab
  dnf:
    name: "{{ GITLAB_PACKAGE_VER }}"
  environment:
    EXTERNAL_URL: https://{{ GITLAB_FQDN }}
  become: true

- name: Gitlab was successfully installed. You can log in to https://{{ GITLAB_FQDN }} as root. Its password is written in /etc/gitlab/initial_root_password. 
  assert: { that: true, quiet: true }
