---
- name: roles/server-cert/tasks/server.yml
  assert: { that: true, quiet: true }

- name: Prepare working directory
  file:
    path: "{{ PCA_SERVER_HOME }}"
    state: directory

- name: Server certs for server1 - Set config file for openssl
  template:
    src: server1.conf
    dest: "{{ PCA_SERVER_HOME }}/{{ PCA_HOSTNAME }}.conf"

- name: Server certs for server2 - Set config file for openssl
  template:
    src: server2.conf
    dest: "{{ PCA_SERVER_HOME }}/{{ PCA_HOSTNAME2 }}.conf"

- name: Create keys and csrs for server1,2
  command: openssl req -new -config {{ item }}.conf \
    -out {{ item }}.csr \
    -keyout {{ item }}.key
  args:
    chdir: "{{ PCA_SERVER_HOME }}" 
  loop:
    - "{{ PCA_HOSTNAME }}"
    - "{{ PCA_HOSTNAME2 }}"

- name: Issue server certs under our sub-ca
  command: openssl ca -config {{ PCA_SUBCA_HOME }}/sub-ca.conf \
    -batch \
    -in {{ item }}.csr \
    -out {{ item }}.crt \
    -extensions server_ext
  args:
    chdir: "{{ PCA_SERVER_HOME }}" 
  loop:
    - "{{ PCA_HOSTNAME }}"
    - "{{ PCA_HOSTNAME2 }}"
