---
- name: roles/private-ca/tasks/certs.yml
  assert: { that: true, quiet: true }

# --- Try and Error start ---

# fileglob runs at project directory basis.
- name: Remember conf file names
  set_fact:
    confs: "{{ 'roles/server-cert/templates/*.conf' | fileglob }}"

- debug: var=confs

- name: Extract basenames without extentions
  set_fact:
    confs: "{{ item | regex_replace('roles/server-cert/templates/', '') }}"
  loop: "{{ confs }}"

- debug: var=confs

# --- Try and Error end ---

- name: Prepare working directory
  file:
    path: "{{ PCA_SERVER_HOME }}"
    state: directory

- name: Server certs - Set config file for openssl
  template:
    src: "{{ item }}"
    dest: "{{ PCA_SERVER_HOME }}/"
  with_fileglob: '../templates/*.conf'
  tags: server

- name: Create keys and csrs for each server(s)
  command: openssl req -new -config server1.conf \
    -out server1.csr \
    -keyout server1.key
  args:
    chdir: "{{ PCA_SERVER_HOME }}" 

- name: Issue server certs under our sub-ca
  command: openssl ca -config {{ PCA_SUBCA_HOME }}/sub-ca.conf \
    -batch \
    -in server1.csr \
    -out server1.crt \
    -extensions server_ext
  args:
    chdir: "{{ PCA_SERVER_HOME }}" 
