---
- name: roles/ldap-auth/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Install dependency
  dnf:
    name: 
      - sssd
      - sssd-tools
      - oddjob
  become: true

- name: activate oddjobd
  systemd:
    name: oddjobd
    state: started
    enabled: true
  become: true
