---
- name: roles/private-ca/tasks/main.yml
  assert: { that: true, quiet: true }

- debug: var=PCA_HOSTNAME

- name: Delete base directory
  file:
    path: "{{ PCA_BASEDIR }}"
    state: absent
  become: True
  when: PCA_OVERWRITE

- name: Check if rootca has already been created
  stat:
    path: "{{ PCA_ROOTCA_HOME }}"
  register: rootca_home

- import_tasks: root-ca.yml
  when: not rootca_home.stat.exists

- name: Check if sub has already been created
  stat:
    path: "{{ PCA_SUBCA_HOME }}"
  register: subca_home

- import_tasks: sub-ca.yml
  when: not subca_home.stat.exists
