---
- name: roles/prometheus/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Unarchive prometheus archive file
  ansible.builtin.unarchive:
    src: "{{ PRMT_ARCHIVE_URL }}"
    remote_src: true
    dest: /opt
  become: true

- name: Create symlink
  file:
    path: "{{ PRMT_SYMLINK }}"
    src: /opt/{{ PRMT_BASENAME }}
    state: link
  become: true

- name: Customize config
  template:
    src: prometheus.yml
    dest: "{{ PRMT_SYMLINK }}/prometheus.yml"
  become: true

- name: Open firewall
  ansible.posix.firewalld:
    port: "{{ PRMT_PORT }}/tcp"
    immediate: yes
    permanent: yes
    state: enabled
  become: yes
  notify: reload firewalld

- name: Deploy environment file
  template:
    src: prometheus
    dest: /etc/sysconfig/
  become: true

- name: Deploy as a service
  template:
    src: prometheus.service
    dest: /etc/systemd/system
  become: yes

- name: Start prometheus service
  systemd:
    name: prometheus.service
    state: started
    enabled: true
    daemon-reload: true
  become: yes
