---
- name: roles/docker/tasks/main.yml
  meta: noop

- name: Install Docker Repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    mode: 0644
  become: true
 
- name: Install Docker
  dnf:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
  become: true

- name: set helper script for (already removed) docker-compose command
  template:
    src: docker-compose
    dest: /usr/local/bin/
    mode: 0755
  become: true

- name: Start and enable docker
  systemd:
    name: docker
    enabled: true
    state: started
  become: true

- name: Enable docker commands for ordinary user
  file:
    path: /var/run/docker.sock
    mode: 0666   
  become: true
  when: DOCKER_ENABLED_FOR_ANYONE
