---
- name: roles/base/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Install guest addition
  dnf:
    name: open-vm-tools
  become: yes
  when: ansible_product_name is match('VMware')
