---
- name: roles/base/tasks/joe.yml
  assert: { that: true, quiet: true }

- name: disable wordwrap in joe editor
  replace:
    path: /etc/joe/ftyperc
    regexp: ^-wordwrap
    replace: " -wordwrap"
  become: yes
