---
- name: roles/base/tasks/mandatory.yml
  assert: { that: true, quiet: true }

- name: Install mandatory packages
  dnf: 
    name:
      - chrony
      - glibc-devel
      - gcc-c++
      - python3-passlib
      - python3-libselinux
      - git
      - patch
      - rsync
      - vim-enhanced
      - nkf
      - bind-utils
      - unzip
      - bzip2
      - wget
      - w3m
      - kernel-devel
      - man
      - npm
      - joe
      - perl-ExtUtils-MakeMaker
      - wireshark
      - strace
      - libsmi
      - jq
      - nano
      - python-dnf
      - python3-pip
      - ansible-lint
      - perl
      - postfix
      - msmtp
  become: yes

- name: Install additional packages for AlmaLinux
  dnf:
    name:
      - man-pages
      - man-pages-overrides
  become: yes
