---
- name: roles/base/tasks/selinux.yml
  set_fact: dummy=0

- name: Install tools required for disabling selinux
  dnf: 
    name: python3-libselinux
    state: present
  become: yes

# on RHEL9/Alma9 etc, selinux will never be disabled by this way. This makes it just "permissive".
- name: Disable selinux 
  ansible.posix.selinux:
    state: disabled
  become: yes
