---
- name: roles/base/tasks/selinux.yml
  assert: { that: true, quiet: true }

- name: Install tools required for disabling selinux
  dnf: 
    name: python3-libselinux
    state: present
  become: yes

- name: Disable selinux 
  ansible.posix.selinux:
    state: disabled
  become: yes

- name: Note that selinux will never be disabled by this way on RHEL9 and its derivatives. We've just made it "permissive".
  assert: { that: true, quiet: true }
