---
- name: roles/php/tasks/main.yml
  assert: { that: true, quiet: true }

- name: Check if {{ PHP_COMPOSER_BIN }}
  stat:
    path: "{{ PHP_COMPOSER_BIN }}"
  register: composer

- import_tasks: php.yml
  when: not composer.stat.exists

- import_tasks: composer.yml
  when: not composer.stat.exists

